[versions]
pluginYmlPaper = "0.9.0"
paperApi = "26.1.1.build.+"
worldedit = "7.4.2"
worldguard = "7.0.16"
dynmap = "3.7-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
worldedit =  { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref  = "worldedit" }
worldguard =  { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref  = "worldguard" }
dynmap =  { group = "us.dynmap", name = "DynmapCoreAPI", version.ref  = "dynmap" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }
